import React from "react";
import SortIcon from "../../assets/SortIcon";
import SortDuoIcon from "../../assets/SortDuoIcon";
import { Modal } from "antd";
import MagnifyIcon from "../../assets/MagnifyIcon";

type Props = {
  setFilters: React.Dispatch<React.SetStateAction<Record<string, any>>>;
  filters: Record<string, any>;
  title: string;
  searchName?: string;
  sortName?: string;
  filterOptions?: { label: string; value: string }[];
};

function CustomHeaderTable({
  setFilters,
  filters,
  title,
  searchName,
  sortName,
  filterOptions,
}: Props) {
  const [sortName1, sortValue] = filters.sort?.split(",");

  return (
    <div className="flex gap-2">
      <p className="mr-auto">{title}</p>

      {/* Sort */}
      {sortName && (
        <button
          onClick={() => {
            setFilters((prev) => {
              return {
                ...prev,
                sort:
                  sortName1 === sortName
                    ? sortValue === "desc"
                      ? `${sortName},asc`
                      : `${sortName},desc`
                    : `${sortName},asc`,
              };
            });
          }}
        >
          <div
            className={`w-5 h-5 transition ${
              sortName === sortName1 && sortValue === "asc" ? "rotate-180" : ""
            }`}
          >
            {sortName === sortName1 ? <SortIcon /> : <SortDuoIcon />}
          </div>
        </button>
      )}

      {/* Search */}
      {searchName && (
        <button
          onClick={() => {
            Modal.info({
              title: "Report ID",
              okButtonProps: {
                className: "bg-p500",
              },
              maskClosable: true,
              content: (
                <div>
                  <p>
                    This is the unique identifier of the report. It is
                    automatically generated by the system.
                  </p>
                </div>
              ),
            });
          }}
        >
          <div className="w-5 h-5">
            <MagnifyIcon />
          </div>
        </button>
      )}
    </div>
  );
}

export default CustomHeaderTable;
